### ISSUE TITLE
一点困惑

### ISSUE THREAD

**Issue by tiancihui** [dodng/fast_ring_queue#2]
无锁队列本质上还是有锁，只不过锁的粒度很小，通常是一个标志。
一般通过CAS（compare&set）和TAS（test&set）等原子操作结合忙等待实现的
`
`if (tag_p->tag_value == CAN_WRITE) 
`{  
`		user_data = (u_char *)g_p + sizeof(TAG);
`		tag_p->tag_value = WRITING;
`} 
`
我看你的实现代码里面，判断和写标志并不是原子的操作？是否还是会有多线程的问题？有点疑惑，
期待您解答下。

**Comment by dodng** [comment]
hi,你好。我写的这个适合2个线程，1个写，1个读。在linux环境中，我的这个使用方式对于char的操作就是原子操作的，谢谢

**Comment by tiancihui** [comment]
嗯，好的，谢谢您的解答
